# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Agent1

stages:
- stage: Checkmarx
  jobs:
  - job: Checkmarx
    displayName: Checkmarx

    steps:
      - task: Application security testing@2022
        displayName: 'Application security testing'
        inputs:
          enableSastScan: true
          projectName: '$(Build.DefinitionName)'
          syncMode: true
          forceScan: true
          CheckmarxService: SAST LAB
          preset: 'High and Medium'
          engineConfigId: 5
          overrideProjectSettings: false
          fullTeamName: 'CxServer'
          fullScansScheduled: true
          fullScanCycle: 2
          folderExclusion: 'cvs, .svn, .hg , .git, .bzr, bin , obj,  backup, .idea, node_modules, $(cx_exclude_folders)'
          scanTimeout: 60
          vulnerabilityThreshold: false
          high: 0
          medium: 1
          low: 1
