version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: sudo apt-get install -y git
      - run: |
          wget https://download.checkmarx.com/9.3.0GA/Plugins/CxConsolePlugin-1.1.5.zip
          mkdir CxConsolePlugin
          unzip CxConsolePlugin-1.1.5.zip -d CxConsolePlugin
          cd CxConsolePlugin
          chmod +x runCxConsole.sh
          echo $CIRCLE_PROJECT_REPONAME
          ls $CIRCLE_PROJECT_REPONAME
          ./runCxConsole.sh Scan -CxServer $CX_HOST -TrustedCertificates -CxUser $CX_USER -CxPassword $CX_PASS -LocationType "folder" -Projectname CxServer/SP/Partners/Nova8/$CIRCLE_PROJECT_REPONAME -LocationPath $CIRCLE_PROJECT_REPONAME -Comment "Build Id : $CI_PIPELINE_ID" -ForceScan
workflows:
  build_scan: 
    jobs:
      - build-and-test
