version: 2.1

jobs:
  checkmarx-sast:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: echo "TEST CONNECTION"
      - run: ifconfig
      
  
workflows:
  build_scan: 
    jobs:
      - checkmarx-sast
