version: 2.1

jobs:
  checkmarx-sast:  
    circleci_ip_ranges: true
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: echo "TEST CONNECTION"
      - run: curl ifconfig.me
      - run: traceroute dftsast.checkmarx.net    
      
      
  
workflows:
  build_scan: 
    jobs:
      - checkmarx-sast
