version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: sudo apt-get install -y git
      - run: echo "TEST CONNECTION $CX_HOST"
      - run:  curl -IL $CX_HOST
  
workflows:
  build_scan: 
    jobs:
      - build-and-test
